LABEL Boot MBR on first hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd0 0
TEXT HELP
                 Boot from First Hard Drive.
ENDTEXT

LABEL Boot partition #1 on first hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd0 1
TEXT HELP
                 Boot from 1st Partition on First Hard Drive.
ENDTEXT

LABEL Boot partition #2 on first hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd0 2
TEXT HELP
                 Boot from 2nd Partition on First Hard Drive.
ENDTEXT

LABEL Boot partition #3 on first hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd0 3
TEXT HELP
                 Boot from 3rd Partition on First Hard Drive.
ENDTEXT

LABEL Boot partition #4 on first hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd0 4
TEXT HELP
                 Boot from 4th Partition on First Hard Drive.
ENDTEXT

LABEL Boot MBR on second hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd1 0
TEXT HELP
                 Boot from Second Hard Drive.
ENDTEXT

LABEL Boot partition #1 on second hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd1 1
TEXT HELP
                 Boot from 1st Partition on Second Hard Drive.
ENDTEXT

LABEL Boot partition #2 on second hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd1 2
TEXT HELP
                 Boot from 2nd Partition on Second Hard Drive.
ENDTEXT

LABEL Boot partition #3 on second hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd1 3
TEXT HELP
                 Boot from 3rd Partition on Second Hard Drive.
ENDTEXT

LABEL Boot partition #4 on second hard drive!
KERNEL boot/isolinux/chain.c32
APPEND hd1 4
TEXT HELP
                 Boot from 4th Partition on Second Hard Drive.
ENDTEXT
